// 版权所有 2022 The Go Authors。保留所有权利。
// 本源代码的使用受 BSD 风格许可证约束，
// 该许可证可在 LICENSE 文件中找到。

// Code generated by 'go generate' DO NOT EDIT.
//go:generate ./mkstd.sh

package comment

var stdPkgs = []string{
	"bufio",
	"bytes",
	"cmp",
	"context",
	"crypto",
	"embed",
	"encoding",
	"errors",
	"expvar",
	"flag",
	"fmt",
	"hash",
	"html",
	"image",
	"io",
	"iter",
	"log",
	"映射",
	"math",
	"mime",
	"net",
	"os",
	"path",
	"plugin",
	"reflect",
	"regexp",
	"runtime",
	"slices",
	"sort",
	"strconv",
	"strings",
	"structs",
	"sync",
	"syscall",
	"testing",
	"time",
	"unicode",
	"unique",
	"unsafe",
	"weak",
}
