// Code generated by 'simdgen -o godefs -goroot $GOROOT -xedPath $XED_PATH go.yaml types.yaml categories.yaml'; DO NOT EDIT.

//go:build goexperiment.simd

package archsimd

import "internal/cpu"

type X86Features struct{}

var X86 X86Features

// AES 返回 CPU 是否支持 AES 功能。
//
// AES 在所有 GOARCH 上定义，但仅在
// GOARCH amd64 上返回 true。
func (X86Features) AES() bool {
	return cpu.X86.HasAES
}

// AVX 返回 CPU 是否支持 AVX 功能。
//
// AVX 在所有 GOARCH 上定义，但仅在
// GOARCH amd64 上返回 true。
func (X86Features) AVX() bool {
	return cpu.X86.HasAVX
}

// AVX2 返回 CPU 是否支持 AVX2 功能。
//
// AVX2 在所有 GOARCH 上定义，但仅在
// GOARCH amd64 上返回 true。
func (X86Features) AVX2() bool {
	return cpu.X86.HasAVX2
}

// AVX512 返回 CPU 是否支持 AVX512F+CD+BW+DQ+VL 功能。
//
// 这五个 CPU 功能捆绑在一起，AVX-512 的使用
// 只有在所有这些功能一起支持时才被允许。
// 几乎每个支持 AVX-512 的 CPU 都
// 支持这五个功能中的所有功能。
//
// AVX512 在所有 GOARCH 上定义，但仅在
// GOARCH amd64 上返回 true。
func (X86Features) AVX512() bool {
	return cpu.X86.HasAVX512
}

// AVX512BITALG 返回 CPU 是否支持 AVX512BITALG 功能。
//
// AVX512BITALG 在所有 GOARCH 上定义，但仅在
// GOARCH amd64 上返回 true。
func (X86Features) AVX512BITALG() bool {
	return cpu.X86.HasAVX512BITALG
}

// AVX512GFNI 返回 CPU 是否支持 AVX512GFNI 功能。
//
// AVX512GFNI 在所有 GOARCH 上定义，但仅在
// GOARCH amd64 上返回 true。
func (X86Features) AVX512GFNI() bool {
	return cpu.X86.HasAVX512GFNI
}

// AVX512VAES 返回 CPU 是否支持 AVX512VAES 功能。
//
// AVX512VAES 在所有 GOARCH 上定义，但仅在
// GOARCH amd64 上返回 true。
func (X86Features) AVX512VAES() bool {
	return cpu.X86.HasAVX512VAES
}

// AVX512VBMI 返回 CPU 是否支持 AVX512VBMI 功能。
//
// AVX512VBMI 在所有 GOARCH 上定义，但仅在
// GOARCH amd64 上返回 true。
func (X86Features) AVX512VBMI() bool {
	return cpu.X86.HasAVX512VBMI
}

// AVX512VBMI2 返回 CPU 是否支持 AVX512VBMI2 功能。
//
// AVX512VBMI2 在所有 GOARCH 上定义，但仅在
// GOARCH amd64 上返回 true。
func (X86Features) AVX512VBMI2() bool {
	return cpu.X86.HasAVX512VBMI2
}

// AVX512VNNI 返回 CPU 是否支持 AVX512VNNI 功能。
//
// AVX512VNNI 在所有 GOARCH 上定义，但仅在
// GOARCH amd64 上返回 true。
func (X86Features) AVX512VNNI() bool {
	return cpu.X86.HasAVX512VNNI
}

// AVX512VPCLMULQDQ 返回 CPU 是否支持 AVX512VPCLMULQDQ 功能。
//
// AVX512VPCLMULQDQ 在所有 GOARCH 上定义，但仅在
// GOARCH amd64 上返回 true。
func (X86Features) AVX512VPCLMULQDQ() bool {
	return cpu.X86.HasAVX512VPCLMULQDQ
}

// AVX512VPOPCNTDQ 返回 CPU 是否支持 AVX512VPOPCNTDQ 功能。
//
// AVX512VPOPCNTDQ 在所有 GOARCH 上定义，但仅在
// GOARCH amd64 上返回 true。
func (X86Features) AVX512VPOPCNTDQ() bool {
	return cpu.X86.HasAVX512VPOPCNTDQ
}

// AVXVNNI 返回 CPU 是否支持 AVXVNNI 功能。
//
// AVXVNNI 在所有 GOARCH 上定义，但仅在
// GOARCH amd64 上返回 true。
func (X86Features) AVXVNNI() bool {
	return cpu.X86.HasAVXVNNI
}

// SHA 返回 CPU 是否支持 SHA 功能。
//
// SHA 在所有 GOARCH 上定义，但仅在
// GOARCH amd64 上返回 true。
func (X86Features) SHA() bool {
	return cpu.X86.HasSHA
}
