// Code generated by gen_sort_variants.go; DO NOT EDIT.

// Copyright 2022 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package sort

// insertionSort 使用插入排序对 data[a:b] 进行排序。
func insertionSort(data Interface, a, b int) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && data.Less(j, j-1); j-- {
			data.Swap(j, j-1)
		}
	}
}

// siftDown 在 data[lo:hi] 上实现堆属性。
// first 是数组中堆根所在位置的偏移量。
func siftDown(data Interface, lo, hi, first int) {
	root := lo
	for {
		child := 2*root + 1
		if child >= hi {
			break
		}
		if child+1 < hi && data.Less(first+child, first+child+1) {
			child++
		}
		if !data.Less(first+root, first+child) {
			return
		}
		data.Swap(first+root, first+child)
		root = child
	}
}

func heapSort(data Interface, a, b int) {
	first := a
	lo := 0
	hi := b - a

	// 构建堆，最大的元素在顶部。
	for i := (hi - 1) / 2; i >= 0; i-- {
		siftDown(data, i, hi, first)
	}

	// 弹出元素，最大的优先，进入数据末尾。
	for i := hi - 1; i >= 0; i-- {
		data.Swap(first, first+i)
		siftDown(data, lo, i, first)
	}
}

// pdqsort 对 data[a:b] 进行排序。
// 该算法基于pattern-defeating quicksort(pdqsort)，但不包含BlockQuicksort的优化。
// pdqsort 论文：https://arxiv.org/pdf/2106.05123.pdf
// C++ 实现：https://github.com/orlp/pdqsort
// Rust 实现：https://docs.rs/pdqsort/latest/pdqsort/
// limit 是在回退到 heapsort 之前允许的不良（非常不平衡）枢轴的数量。
func pdqsort(data Interface, a, b, limit int) {
	const maxInsertion = 12

	var (
		wasBalanced    = true // 上一次分割是否相对平衡
		wasPartitioned = true // 切片是否已经被分割
	)

	for {
		length := b - a

		if length <= maxInsertion {
			insertionSort(data, a, b)
			return
		}

		// 如果做出了太多不良选择，回退到 heapsort。
		if limit == 0 {
			heapSort(data, a, b)
			return
		}

		// 如果上一次分割不平衡，我们需要破坏模式。
		if !wasBalanced {
			breakPatterns(data, a, b)
			limit--
		}

		pivot, hint := choosePivot(data, a, b)
		if hint == decreasingHint {
			reverseRange(data, a, b)
			// 所选枢轴是数组开始后的 pivot-a 个元素。
			// 反转后是数组末尾前的 pivot-a 个元素。
			// 这个想法来自 Rust 的实现。
			pivot = (b - 1) - (pivot - a)
			hint = increasingHint
		}

		// 切片可能已经排序。
		if wasBalanced && wasPartitioned && hint == increasingHint {
			if partialInsertionSort(data, a, b) {
				return
			}
		}

		// 切片可能包含许多重复元素，将切片分割为等于枢轴的元素和大于枢轴的元素。
		if a > 0 && !data.Less(a-1, pivot) {
			mid := partitionEqual(data, a, b, pivot)
			a = mid
			continue
		}

		mid, alreadyPartitioned := partition(data, a, b, pivot)
		wasPartitioned = alreadyPartitioned

		leftLen, rightLen := mid-a, b-mid
		balanceThreshold := length / 8
		if leftLen < rightLen {
			wasBalanced = leftLen >= balanceThreshold
			pdqsort(data, a, mid, limit)
			a = mid + 1
		} else {
			wasBalanced = rightLen >= balanceThreshold
			pdqsort(data, mid+1, b, limit)
			b = mid
		}
	}
}

// partition 进行一次快速排序分割。
// 设 p = data[pivot]
// 移动 data[a:b] 中的元素，使得 data[i]<p 且 data[j]>=p，其中 i<newpivot 且 j>newpivot。
// 返回时，data[newpivot] = p
func partition(data Interface, a, b, pivot int) (newpivot int, alreadyPartitioned bool) {
	data.Swap(a, pivot)
	i, j := a+1, b-1 // i 和 j 包括待分割元素的范围

	for i <= j && data.Less(i, a) {
		i++
	}
	for i <= j && !data.Less(j, a) {
		j--
	}
	if i > j {
		data.Swap(j, a)
		return j, true
	}
	data.Swap(i, j)
	i++
	j--

	for {
		for i <= j && data.Less(i, a) {
			i++
		}
		for i <= j && !data.Less(j, a) {
			j--
		}
		if i > j {
			break
		}
		data.Swap(i, j)
		i++
		j--
	}
	data.Swap(j, a)
	return j, false
}

// partitionEqual 将 data[a:b] 分割为等于 data[pivot] 的元素，后跟大于 data[pivot] 的元素。
// 假设 data[a:b] 不包含小于 data[pivot] 的元素。
func partitionEqual(data Interface, a, b, pivot int) (newpivot int) {
	data.Swap(a, pivot)
	i, j := a+1, b-1 // i 和 j 包括待分割元素的范围

	for {
		for i <= j && !data.Less(a, i) {
			i++
		}
		for i <= j && data.Less(a, j) {
			j--
		}
		if i > j {
			break
		}
		data.Swap(i, j)
		i++
		j--
	}
	return i
}

// partialInsertionSort 部分排序一个切片，如果切片在最后已排序则返回 true。
func partialInsertionSort(data Interface, a, b int) bool {
	const (
		maxSteps         = 5  // 将被移动的相邻无序对的最大数量
		shortestShifting = 50 // 在短数组上不移动任何元素
	)
	i := a + 1
	for j := 0; j < maxSteps; j++ {
		for i < b && !data.Less(i, i-1) {
			i++
		}

		if i == b {
			return true
		}

		if b-a < shortestShifting {
			return false
		}

		data.Swap(i, i-1)

		// 将较小的元素向左移动。
		if i-a >= 2 {
			for j := i - 1; j >= 1; j-- {
				if !data.Less(j, j-1) {
					break
				}
				data.Swap(j, j-1)
			}
		}
		// 将较大的元素向右移动。
		if b-i >= 2 {
			for j := i + 1; j < b; j++ {
				if !data.Less(j, j-1) {
					break
				}
				data.Swap(j, j-1)
			}
		}
	}
	return false
}

// breakPatterns 分散一些元素，试图破坏可能导致快速排序中不平衡分割的某些模式。
func breakPatterns(data Interface, a, b int) {
	length := b - a
	if length >= 8 {
		random := xorshift(length)
		modulus := nextPowerOfTwo(length)

		for idx := a + (length/4)*2 - 1; idx <= a+(length/4)*2+1; idx++ {
			other := int(uint(random.Next()) & (modulus - 1))
			if other >= length {
				other -= length
			}
			data.Swap(idx, a+other)
		}
	}
}

// choosePivot 在 data[a:b] 中选择一个枢轴。
//
// [0,8): 选择一个静态枢轴。
// [8,shortestNinther): 使用简单的三元素中位数方法。
// [shortestNinther,∞): 使用 Tukey 九元素中位数方法。
func choosePivot(data Interface, a, b int) (pivot int, hint sortedHint) {
	const (
		shortestNinther = 50
		maxSwaps        = 4 * 3
	)

	l := b - a

	var (
		swaps int
		i     = a + l/4*1
		j     = a + l/4*2
		k     = a + l/4*3
	)

	if l >= 8 {
		if l >= shortestNinther {
			// Tukey 九元素中位数方法，想法来自 Rust 的实现。
			i = medianAdjacent(data, i, &swaps)
			j = medianAdjacent(data, j, &swaps)
			k = medianAdjacent(data, k, &swaps)
		}
		// 在 i、j、k 中找到中位数并将其存储到 j。
		j = median(data, i, j, k, &swaps)
	}

	switch swaps {
	case 0:
		return j, increasingHint
	case maxSwaps:
		return j, decreasingHint
	default:
		return j, unknownHint
	}
}

// order2 返回 x，y，其中 data[x] <= data[y]，x，y=a，b 或 x，y=b，a。
func order2(data Interface, a, b int, swaps *int) (int, int) {
	if data.Less(b, a) {
		*swaps++
		return b, a
	}
	return a, b
}

// median 返回 x，其中 data[x] 是 data[a]、data[b]、data[c] 的中位数，x 是 a、b 或 c。
func median(data Interface, a, b, c int, swaps *int) int {
	a, b = order2(data, a, b, swaps)
	b, c = order2(data, b, c, swaps)
	a, b = order2(data, a, b, swaps)
	return b
}

// medianAdjacent 找到 data[a - 1]、data[a]、data[a + 1] 的中位数并将索引存储到 a。
func medianAdjacent(data Interface, a int, swaps *int) int {
	return median(data, a-1, a, a+1, swaps)
}

func reverseRange(data Interface, a, b int) {
	i := a
	j := b - 1
	for i < j {
		data.Swap(i, j)
		i++
		j--
	}
}

func swapRange(data Interface, a, b, n int) {
	for i := 0; i < n; i++ {
		data.Swap(a+i, b+i)
	}
}

func stable(data Interface, n int) {
	blockSize := 20 // 必须 > 0
	a, b := 0, blockSize
	for b <= n {
		insertionSort(data, a, b)
		a = b
		b += blockSize
	}
	insertionSort(data, a, n)

	for blockSize < n {
		a, b = 0, 2*blockSize
		for b <= n {
			symMerge(data, a, a+blockSize, b)
			a = b
			b += 2 * blockSize
		}
		if m := a + blockSize; m < n {
			symMerge(data, a, m, n)
		}
		blockSize *= 2
	}
}

// symMerge 使用 Pok-Son Kim 和 Arne Kutzner 的 SymMerge 算法合并
// 两个排序的子序列 data[a:m] 和 data[m:b]，"Stable Minimum Storage Merging by Symmetric Comparisons"，
// 在 Susanne Albers 和 Tomasz Radzik 编辑的《Algorithms - ESA 2004》中，
// 计算机科学讲义卷 3221，第 714-723 页。Springer，2004。
//
// 设 M = m-a 和 N = b-n。不失一般性，M < N。
// 递归深度受 ceil(log(N+M)) 限制。
// 该算法需要 O(M*log(N/M + 1)) 次对 data.Less 的调用。
// 该算法需要 O((M+N)*log(M)) 次对 data.Swap 的调用。
//
// 论文给出 O((M+N)*log(M)) 作为赋值数量，假设一个旋转算法
// 使用 O(M+N+gcd(M+N)) 次赋值。论文中的论证对 Swap 操作同样适用，
// 特别是因为块交换旋转仅使用 O(M+N) 次 Swap。
//
// symMerge 假设非退化参数：a < m && m < b。
// 让调用者检查此条件可以消除许多叶子递归调用，这提高了性能。
func symMerge(data Interface, a, m, b int) {
	// 通过直接将 data[a] 插入到 data[m:b]
	// 来避免 symMerge 的不必要递归，如果 data[a:m] 只包含一个元素。
	if m-a == 1 {
		// 使用二进制搜索找到最小索引 i，
		// 使得对于 m <= i < b，data[i] >= data[a]。
		// 如果不存在这样的索引，则以 i == b 退出搜索循环。
		i := m
		j := b
		for i < j {
			h := int(uint(i+j) >> 1)
			if data.Less(h, a) {
				i = h + 1
			} else {
				j = h
			}
		}
		// 交换值直到 data[a] 到达 i 之前的位置。
		for k := a; k < i-1; k++ {
			data.Swap(k, k+1)
		}
		return
	}

	// 通过直接将 data[m] 插入到 data[a:m]
	// 来避免 symMerge 的不必要递归，如果 data[m:b] 只包含一个元素。
	if b-m == 1 {
		// 使用二进制搜索找到最小索引 i，
		// 使得对于 a <= i < m，data[i] > data[m]。
		// 如果不存在这样的索引，则以 i == m 退出搜索循环。
		i := a
		j := m
		for i < j {
			h := int(uint(i+j) >> 1)
			if !data.Less(m, h) {
				i = h + 1
			} else {
				j = h
			}
		}
		// 交换值直到 data[m] 到达位置 i。
		for k := m; k > i; k-- {
			data.Swap(k, k-1)
		}
		return
	}

	mid := int(uint(a+b) >> 1)
	n := mid + m
	var start, r int
	if m > mid {
		start = n - b
		r = mid
	} else {
		start = a
		r = m
	}
	p := n - 1

	for start < r {
		c := int(uint(start+r) >> 1)
		if !data.Less(p-c, c) {
			start = c + 1
		} else {
			r = c
		}
	}

	end := n - start
	if start < m && m < end {
		rotate(data, start, m, end)
	}
	if a < start && start < mid {
		symMerge(data, a, start, mid)
	}
	if mid < end && end < b {
		symMerge(data, mid, end, b)
	}
}

// rotate 在数据中旋转两个连续块 u = data[a:m] 和 v = data[m:b]：
// 形式为 'x u v y' 的数据变为 'x v u y'。
// rotate 最多执行 b-a 次对 data.Swap 的调用，
// 并假设非退化参数：a < m && m < b。
func rotate(data Interface, a, m, b int) {
	i := m - a
	j := b - m

	for i != j {
		if i > j {
			swapRange(data, m-i, m, j)
			i -= j
		} else {
			swapRange(data, m-i, m+j-i, i)
			j -= i
		}
	}
	// i == j
	swapRange(data, m-i, m, i)
}
