// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/array.go

// 版权所有 2011 The Go Authors。保留所有权利。
// 本源代码的使用受 BSD 风格许可证约束，
// 该许可证可在 LICENSE 文件中找到。

package types

// 一个Array represents an array type.
type Array struct {
	len  int64
	elem Type
}

// NewArray 返回a new array type for the given element type and length.
// 一个negative length indicates an unknown length.
func NewArray(elem Type, len int64) *Array { return &Array{len: len, elem: elem} }

// Len 返回the length of array a.
// 一个negative result indicates an unknown length.
func (a *Array) Len() int64 { return a.len }

// Elem 返回element type of array a.
func (a *Array) Elem() Type { return a.elem }

func (a *Array) Underlying() Type { return a }
func (a *Array) String() string   { return TypeString(a, nil) }
