// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/under.go

// 版权所有 2011 The Go Authors。保留所有权利。
// 本源代码的使用受 BSD 风格许可证约束，
// 该许可证可在 LICENSE 文件中找到。

package types

import "iter"

// If typ 是一个 type parameter, underIs 返回 result of typ.underIs(f).
// Otherwise, underIs 返回 result of f(typ.Underlying()).
func underIs(typ Type, f func(Type) bool) bool {
	return all(typ, func(_, u Type) bool {
		return f(u)
	})
}

// all 报告whether f(t, u) 为真 for all (type/underlying type)
// pairs in the typeset of t. See [typeset] for details of sequence.
func all(t Type, f func(t, u Type) bool) bool {
	if p, _ := Unalias(t).(*TypeParam); p != nil {
		return p.typeset(f)
	}
	return f(t, t.Underlying())
}

// typeset 是一个n iterator over the (type/underlying type) pairs of the
// specific type terms 的类型 set implied by t.
// If t 是一个 type parameter, the implied type set 是 type set of t's constraint.
// In that case, if there are no specific terms, typeset calls yield with (nil, nil).
// If t is not a type parameter, the implied type set consists of just t.
// In any case, typeset is guaranteed to call yield at least once.
func typeset(t Type) iter.Seq2[Type, Type] {
	return func(yield func(t, u Type) bool) {
		_ = all(t, yield)
	}
}

// 一个typeError 描述 a type error.
type typeError struct {
	format_ string
	args    []any
}

var emptyTypeError typeError

func typeErrorf(format string, args ...any) *typeError {
	if format == "" {
		return &emptyTypeError
	}
	return &typeError{format, args}
}

// format formats a type error as a string.
// check 可能是 nil.
func (err *typeError) format(check *Checker) string {
	return check.sprintf(err.format_, err.args...)
}

// If t 是一个 type parameter, cond is nil, and t's type set 包含 no channel types,
// commonUnder 返回the common underlying type of all types in t's type set if
// it exists, or nil and a type error otherwise.
//
// If t 是一个 type parameter, cond is nil, and there are channel types, t's type set
// must only contain channel types, they must all have the same element types,
// channel directions must not conflict, and commonUnder returns one of the most
// restricted channels. Otherwise, the function returns nil and a type error.
//
// If cond != nil, each pair (t, u) 类型为 and underlying type in t's type set
// must satisfy the condition expressed by cond. If the result of cond is != nil,
// commonUnder 返回nil and the type error reported by cond.
// Note that cond is called before any other conditions are checked; specifically
// cond 可能是 called with (nil, nil) 如果 type set 包含 no specific types.
//
// If t is not a type parameter, commonUnder behaves as if t was a type parameter
// with the single type t in its type set.
func commonUnder(t Type, cond func(t, u Type) *typeError) (Type, *typeError) {
	var ct, cu Type // type and respective common underlying type
	for t, u := range typeset(t) {
		if cond != nil {
			if err := cond(t, u); err != nil {
				return nil, err
			}
		}

		if u == nil {
			return nil, typeErrorf("no specific type")
		}

		// If this 是 first type we're seeing, we're done.
		if cu == nil {
			ct, cu = t, u
			continue
		}

		// If we've seen a channel before, and we have a channel now, they 必须是 compatible.
		if chu, _ := cu.(*Chan); chu != nil {
			if ch, _ := u.(*Chan); ch != nil {
				if !Identical(chu.elem, ch.elem) {
					return nil, typeErrorf("channels %s and %s have different element types", ct, t)
				}
				// If we have different channel directions, keep the restricted one
				// and complain if they conflict.
				switch {
				case chu.dir == ch.dir:
					// nothing to do
				case chu.dir == SendRecv:
					ct, cu = t, u // switch to restricted channel
				case ch.dir != SendRecv:
					return nil, typeErrorf("channels %s and %s have conflicting directions", ct, t)
				}
				continue
			}
		}

		// Otherwise, the current type must have the same underlying type as all previous types.
		if !Identical(cu, u) {
			return nil, typeErrorf("%s and %s have different underlying types", ct, t)
		}
	}
	return cu, nil
}
